src/Entity/Trip.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TripRepository;
use App\Repository\TripStatusEnum;

#[ORM\Entity(repositoryClass: TripRepository::class)]
class Trip
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

     public $page = 1;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    public ?\DateTime $startDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $endDate = null;

    #[ORM\Column(length: 255)]
    public ?string $startingPoint = null;

    #[ORM\Column(length: 255)]
    public ?string $destination = null;

    #[ORM\Column(type: Types::TIME_IMMUTABLE)]
    private ?\DateTimeImmutable $startingTime = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $endingTime = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?TripStatusEnum $status = null;

    #[ORM\ManyToOne(inversedBy: 'Trip')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Car $car = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'trip')]
    private Collection $user;

    #[ORM\Column(nullable: true)]
    public ?int $places = null;

    #[ORM\ManyToOne(inversedBy: 'trips')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Driver = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTime $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTime $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getStartingPoint(): ?string
    {
        return $this->startingPoint;
    }

    public function setStartingPoint(string $startingPoint): static
    {
        $this->startingPoint = $startingPoint;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): static
    {
        $this->destination = $destination;

        return $this;
    }

    public function getStartingTime(): ?\DateTimeImmutable
    {
        return $this->startingTime;
    }

    public function setStartingTime(\DateTimeImmutable $startingTime): static
    {
        $this->startingTime = $startingTime;

        return $this;
    }

    public function getEndingTime(): ?\DateTime
    {
        return $this->endingTime;
    }

    public function setEndingTime(\DateTime $endingTime): static
    {
        $this->endingTime = $endingTime;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?TripStatusEnum
    {
        return $this->autoStatus();
    }

    
    public function autoStatus(): ?TripStatusEnum
    {
        $now = date_create();

        
        if ($this->startDate && $this->startDate > $now && $this->places && $this->places > 0) {
            return TripStatusEnum::AVAILABLE;
        }

       
        if ($this->endDate && $this->endDate < $now) {
            return TripStatusEnum::PAST;
        }

        if ($this->startDate && $this->endDate && $this->startDate <= $now && $this->endDate >= $now) {
            return TripStatusEnum::ONGOING;
        }


        return $this->status;
    }

    public function setStatus( $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): static
    {
        $this->car = $car;

        return $this;
    }

      /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
            $user->addTrip($this);
             $this->setPlaces($this->places - 1);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->user->removeElement($user)) {
            $user->removeTrip($this);
        }

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(?int $places): static
    {
        $this->places = $places;

        return $this;
    }

    public function getDriver(): ?User
    {
        return $this->Driver;
    }

    public function setDriver(?User $Driver): static
    {
        $this->Driver = $Driver;

        return $this;
    }

  
}

src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\Trip;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'Email'
            ])
           /*  ->add('roles') */
          /*   ->add('password') */
            ->add('name', TextType::class, [
                'label' => 'Prénom'
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Nom'
            ])
            ->add('pseudo')
            ->add('number')
            ->add('adress', TextType::class, [
                'label' => 'Votre adresse'
            ])
            ->add('dob', BirthdayType::class, [
                'label' => 'Date de naissance'
            ])
            ->add('thumbnail', FileType::class, [
                'label' => 'Photo de profile',
                'required' => false
            ])
       /*      ->add('createAt', null, [
                'widget' => 'single_text',
            ])
            ->add('isVerified')
            ->add('trip', EntityType::class, [
                'class' => Trip::class,
                'choice_label' => 'id',
                'multiple' => true,
            ]) */
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\Trip;
use App\Form\ProfileType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/profile', name: 'app_profile')]
final class ProfileController extends AbstractController
{
    #[Route('/', name: '', methods: ['POST','GET'])]
    public function show( EntityManagerInterface $em, Request $request): Response
    {
        $user = $this->getUser();

         if(!$user) 
        {
            return $this->redirectToRoute('app_home');

        }

        $limit =3;
        $page = $request->query-> getInt('page', 1);

        /* dd($user); */
        $data = $em->getRepository(Car::class) -> paginationCarsByUser($user, $limit, $page);
        $dataT = $em->getRepository(Trip::class) -> paginationTripByUser($user, $limit, $page);


        

        return $this->render('profile/index.html.twig', [
            'user' => $user,
            'trips' => $dataT['trip'],
            'cars' => $data['cars'],
            'maxPages' => $data['maxPages'],
           /*  'max' => $data['max'] */
        ]);
    }






    #[Route('/edit', name: '_edit', methods: ['POST','GET'])]
    public function edit( Request $request, EntityManagerInterface $em ): Response
    {

        $user = $this->getUser();
        $form = $this-> createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if(!$user) 
        {
            return $this->redirectToRoute('app_home');

        }

        if($form-> isSubmitted() && $form-> isValid()) {

        

            // Faire les modifications en bdd
            $em-> flush();

            $this-> addFlash('success', "L'utilisateur à été modifié ");


            // rediriger vers le tableau de bord
            return $this->redirectToRoute('app_home');
        }


        return $this->render('profile/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);

    }
}

templates/profile/edit.html.twig
 {% extends 'layout.html.twig' %}

{% block title %}profil de {{user.pseudo}} {% endblock %}

{% block content %}
 
 <main>
        <div class="bg-light-subtle border border-3 border-success rounded p-4 conform mt-4 mb-3">

        <h3>Modification du profil</h3>

            {{ form_errors(form) }}

            {{ form_start(form) }}

            <div class="row my-3">
                <div class="col">
                {{ form_row(form.name) }}
                </div>
                <div class="col">
                    {{ form_row(form.lastName) }}
                </div>
            </div>

            {{ form_row(form.email) }}

            <div class="row my-5">
                <div class="col-sm-8">
                {{ form_row(form.pseudo) }}
                </div>
                <div class="col">
                    {{ form_row(form.number, {
                        label: 'Numero de télephone'
                    }) }}
                </div>
            </div>
                
            <div class="row my-5">
                    <div class="col">
                        {{ form_row(form.dob) }}
                    </div>
                    <div class="col-sm-8">
                        {{ form_row(form.adress) }}
                    </div>
            </div>

                        {{ form_row(form.thumbnail) }}

            <p class="text-end mt-3">
                    <button class="btn btn-lg btn-success" type="submit">
                            Modification
                    </button>
            </p>

            {{ form_end(form) }}

            <div class="text-end">
                <a href="{{ path('app_forgot_password_request')}}"> Changer de mot de passe</a>
            </div> 
        </div>
    </main>

{% endblock %}

templates/profile/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}profil de {{user.pseudo}} {% endblock %}

{% block content %}

 {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}



     <div class="row">
            <aside class="col-xl-3 vh-100 border rounded shadow p-3 m-2">
                    <nav class="nav flex-column">
                        <a class="nav-link active" aria-current="page" href="#"> Page profil</a>
                        <a class="nav-link" href="{{ path('app_car') }}">  {% if cars is not null %} Ajouter un vehicule {% else %} Devenir conducteur
                             {% endif %}  </a>
                        <a class="nav-link" href="{{ path('app_profile_edit') }}">Modifier mes informations</a>
                        {% if cars is not null %} 
                            <a class="nav-link" href="{{ path('app_trip_new') }}"  > Ajouter un trajet</a>
                        {% endif %}      
                    </nav>
            </aside>
            <div class="col text-center">
            <div class="border rounded shadow p-3 m-2 ">

               <h1>{{user.pseudo}}</h1>
               <h2>Bienvenu sur votre espace personel </h2>
               <p> {{user.email}} </p>
               <p> Numero : {{user.number}} </p>
               <p> Adresse : {{user.adress}} </p>
              <small> Inscrit depuis le  {{ user.createAt |date('d/m/Y') }} </small> 
               <p> Date de naissance : {{user.dob |date('d/m/Y')}} </p>
               <h3>Credits : {{user.credits}} </h3>

            </div>
               
            <div class="border rounded shadow p-3 m-2 ">
                    <h2>Vos vehicules</h2>

                    <div class="py-3 row row-cols-1 row-cols-md-1 row-cols-lg-3 g-4">

                        {% for car in cars %}
                            <div class="col-sm-5">
                                <article class="card h-100 border border-success">
                                    <div class="card-body">
                                        <h4 class="card-title h4"> {{car.brand.name}} {{car.model}} {{ car.energy.value}}</h4>
                                        <div class="card-text" > 
                                            {{ car.immatriculation}}
                                        <p>Première immatriculation {{car.firstImmatriculationAt |date('d/m/Y')}} </p>
                                        <p>
                                        Couleur : <input disabled type="color" value"{{car.color}}">
                                        </p>
                                        </div>
                                    </div>
                                    <div class="card-footer text-end">
                                        <a class="btn btn-outline-primary" href="{{ path('app_car_edit', {id: car.id})}}"> Modifier l'article</a>
                                        <a href="{{ path('app_car_delete', {id: car.id} ) }}" class="btn btn-outline-danger">Supprimer</a>
                                    </div>
                                </article>
                            </div>
                        {% endfor %}
                    </div>
            </div>

             <div class="border rounded shadow p-3 m-2 ">
                <h2>Vos Trajets</h2>

                  <div class="py-3 row row-cols-1 row-cols-md-1 row-cols-lg-3 g-4">

                        {% for trip in trips %}
                            <div class="col-sm-5">
                                <article class="card h-100 border border-success">
                                    <div class="card-body">
                                        <h4 class="card-title h4"> {{ trip.startDate ? trip.startDate|format_date( 'full', locale: 'fr') : '' }} </h4>
                                        <button> {{trip.status.value}} </button>
                                        <div class="card-text" > 
                                           <p><strong> {{ trip.startingPoint }} </strong> A {{ trip.startingTime ? trip.startingTime|date('H:i:s') : '' }}<i class="bi bi-dash-lg"></i><strong>{{ trip.destination }}</strong>{{ trip.endingTime ? trip.endingTime|date('H:i:s') : '' }} <br> Heure</p>
                                       
                                      
                                        </div>
                                    </div>
                                    <div class="card-footer text-end">
                                        <button class="btn btn-outline-primary">  {% if trip.driver.pseudo == user.pseudo %} Statut : Conducteur  {% else %}
                                        Statut : Passager
                                            {% endif %}
                                             </button>
                                    </div>
                                </article>
                            </div>
                        {% endfor %}
                    </div>
               
            </div>

     </div>



{% endblock %}